name: way_finder
description: "A new way to find your way"

publish_to: none

version: 2.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bitsdojo_window: ^0.1.6
  provider: ^6.1.2
  flex_color_picker: ^3.4.1
  window_manager: ^0.3.8
  flutter_localizations:
    sdk: flutter
  intl: any
  dynamic_color: ^1.7.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  msix: ^3.16.7

flutter:
  generate: true
  uses-material-design: true
  assets:
    - google_fonts/
